# Generated by Django 5.2.4 on 2025-07-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='product_id',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
