# Generated by Django 5.2.4 on 2025-07-29 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0002_complaint_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_category',
        ),
    ]
