# Generated by Django 5.2.4 on 2025-10-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0003_remove_category_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(default='Profile_imge/default.jpg', upload_to='Profile_imge/'),
        ),
    ]
