# Generated by Django 5.2.4 on 2025-10-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0004_account_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='TypeIs',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary')], default='Secondary', max_length=50),
        ),
    ]
