# Generated by Django 5.2.4 on 2025-12-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0005_productimage_typeis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address_line',
            field=models.JSONField(default=dict),
        ),
    ]
