# Generated by Django 5.2.4 on 2025-12-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0006_alter_account_address_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address_line',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
