# Generated by Django 5.2.4 on 2025-12-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0007_alter_account_address_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
