# Generated by Django 5.2.4 on 2026-01-04 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0008_account_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
