# Generated by Django 5.2.4 on 2026-01-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0009_remove_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='TypeIs',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='Primary_image',
            field=models.ImageField(default='product_images/WhatsApp Image 2026-01-08 at 20.15.48.jpeg', upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='secondary_image',
            field=models.ImageField(default='product_images/WhatsApp Image 2026-01-08 at 20.15.48.jpeg', upload_to='product_images/'),
        ),
    ]
