# Generated by Django 5.2.4 on 2026-01-08 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0010_remove_productimage_typeis_remove_productimage_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='secondary_image',
            new_name='image',
        ),
    ]
