# Generated by Django 5.2.4 on 2026-01-08 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0011_rename_secondary_image_productimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Primary_image',
            new_name='primary_image',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_images', to='commers_API.product'),
        ),
    ]
