# Generated by Django 5.2.4 on 2026-01-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0012_rename_primary_image_product_primary_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_status',
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_address',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_emil',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='payment',
            field=models.CharField(default='On Delivery'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_phone',
            field=models.JSONField(default=dict),
        ),
    ]
