# Generated by Django 5.2.4 on 2026-01-10 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0014_alter_delivery_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='order',
            new_name='delivery_order',
        ),
    ]
