# Generated by Django 5.2.4 on 2026-01-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0015_rename_order_delivery_delivery_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_address',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
