# Generated by Django 5.2.4 on 2026-01-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0016_alter_delivery_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_phone',
            field=models.JSONField(default=list),
        ),
    ]
