# Generated by Django 5.2.4 on 2026-01-12 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0017_alter_delivery_delivery_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_emil',
        ),
    ]
