# Generated by Django 5.2.4 on 2026-01-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0018_remove_delivery_delivery_emil'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='first_name',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='last_name',
            field=models.CharField(default='new', max_length=7),
            preserve_default=False,
        ),
    ]
