# Generated by Django 5.2.4 on 2026-01-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0019_delivery_first_name_delivery_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_address',
            field=models.JSONField(default=dict),
        ),
    ]
