# Generated by Django 5.2.4 on 2026-01-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0022_productcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='color',
            field=models.CharField(choices=[('red', 'أحمر'), ('blue', 'أزرق'), ('green', 'أخضر'), ('yellow', 'أصفر'), ('black', 'أسود'), ('white', 'أبيض'), ('purple', 'بنفسجي'), ('orange', 'برتقالي'), ('pink', 'وردي'), ('brown', 'بني')], default='black', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='color_name',
            field=models.CharField(max_length=20),
        ),
    ]
