# Generated by Django 5.2.4 on 2026-01-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0023_productcolor_color_alter_productcolor_color_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='color',
            field=models.CharField(blank=True, choices=[('red', 'أحمر'), ('blue', 'أزرق'), ('green', 'أخضر'), ('yellow', 'أصفر'), ('black', 'أسود'), ('white', 'أبيض'), ('purple', 'بنفسجي'), ('orange', 'برتقالي'), ('pink', 'وردي'), ('brown', 'بني')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='color_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
