# Generated by Django 5.2.4 on 2026-01-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0024_alter_productcolor_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='color_name',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
