# Generated by Django 5.2.4 on 2026-01-14 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0025_alter_productcolor_color_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcolor',
            unique_together={('product', 'color')},
        ),
    ]
