# Generated by Django 5.2.4 on 2026-01-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0026_alter_productcolor_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
