# Generated by Django 5.2.4 on 2026-02-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0028_orderitem_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='color',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
