# Generated by Django 5.2.4 on 2026-03-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0029_alter_orderitem_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, upload_to='Profile_imge/'),
        ),
    ]
