# Generated by Django 5.2.4 on 2026-03-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0030_alter_account_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='otp_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='otp_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
