# Generated by Django 5.2.4 on 2026-03-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0031_account_otp_code_account_otp_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='isuser',
            field=models.BooleanField(default=True),
        ),
    ]
