# Generated by Django 5.2.4 on 2026-04-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0032_account_isuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='color',
            field=models.CharField(choices=[('red', 'أحمر'), ('blue', 'أزرق'), ('green', 'أخضر'), ('yellow', 'أصفر'), ('black', 'أسود'), ('white', 'أبيض'), ('purple', 'بنفسجي'), ('orange', 'برتقالي'), ('pink', 'وردي'), ('brown', 'بني')], default='black', max_length=20),
        ),
    ]
