# Generated by Django 5.2.4 on 2026-04-07 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0034_remove_attribute_color_category_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='order',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='productcolor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, upload_to='Profile_image/'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='commers_API.order'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='payment',
            field=models.CharField(choices=[('On Delivery', 'On Delivery'), ('Barid mob', 'Barid mob'), ('Bank Transfer', 'Bank Transfer')], default='On Delivery', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='color',
            field=models.CharField(blank=True, default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='commers_API.order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='products', to='commers_API.attribute'),
        ),
        migrations.AlterField(
            model_name='product',
            name='primary_image',
            field=models.ImageField(blank=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='color',
            field=models.CharField(blank=True, choices=[('red', 'أحمر'), ('blue', 'أزرق'), ('green', 'أخضر'), ('yellow', 'أصفر'), ('black', 'أسود'), ('white', 'أبيض'), ('purple', 'بنفسجي'), ('orange', 'برتقالي'), ('pink', 'وردي'), ('brown', 'بني')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='color_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images/'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
