# Generated by Django 5.2.4 on 2026-04-07 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0036_remove_product_stars_product_rating_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('product', 'user')},
        ),
    ]
