# Generated by Django 5.2.4 on 2026-04-07 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0038_alter_review_stars'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
