# Generated by Django 5.2.4 on 2026-04-07 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0040_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
