# Generated by Django 5.2.4 on 2026-04-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0042_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
