# Generated by Django 5.2.4 on 2026-04-07 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0043_alter_review_stars'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
