# Generated by Django 6.0.4 on 2026-04-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0044_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.FloatField(default=0),
        ),
    ]
