# Generated by Django 6.0.4 on 2026-04-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0045_product_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Fast', 'Fast')], default='Normal'),
        ),
    ]
