# Generated by Django 6.0.4 on 2026-04-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0046_delivery_delivery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_type',
            field=models.CharField(choices=[('normal', 'normal'), ('fast', 'fast')], default='normal'),
        ),
    ]
