# Generated by Django 6.0.4 on 2026-04-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0047_alter_delivery_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.FloatField(default=0, max_length=100),
        ),
    ]
