# Generated by Django 6.0.4 on 2026-04-14 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0050_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
