# Generated by Django 6.0.4 on 2026-04-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0052_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='primary_image',
            field=models.ImageField(blank=True, default='product_images/ChatGPT Image Apr 20, 2026, 11_06_52 AM.png', upload_to='product_images/'),
        ),
    ]
