# Generated by Django 6.0.4 on 2026-04-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commers_API', '0053_alter_product_primary_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='primary_image',
            field=models.ImageField(blank=True, default='product_images/defult.png', upload_to='product_images/'),
        ),
    ]
